### ISSUE TITLE
missing mapping.chamberInfo module

### ISSUE THREAD

**Issue by AndrewLevin** [cms-gem-daq-project/gem-plotting-tools#101]
## Brief summary of issue
The ana_scans.py script terminates normally but reports a caught exception. The anaLog.log file shows that an ImportError involving mapping.chamberInfo module occurred.

### Types of issue
Bug report

## Expected Behavior
I have never successfully run the script before.

## Current Behavior
```
[gemuser@gem904qc8daq gemdaq]$ ana_scans.py --scandate=current --ztrim=4 --anaType=scurve  2>&1 | tee -a ana_scurve_log.txt
Running jobs in parallel mode (using Pool(12))
Analysis Requested: scurve
Analysis Requested: scurve
Analysis Requested: scurve
Analysis Requested: scurve
Error: command exited with non-zero code 1
Error: command exited with non-zero code 1
Error: command exited with non-zero code 1
Error: command exited with non-zero code 1
[1, 1, 1, 1]
Normal termination
Results: [1, 1, 1, 1]
Caught non-Python Exception <type 'exceptions.SystemExit'>
[gemuser@gem904qc8daq current]$ cat /data/bigdisk/GEM-Data-Taking/GE11_QC8//GE11-VII-S-CERN-0001/scurve/current/anaLog.log | tail -n8
Traceback (most recent call last):
  File "/opt/cmsgemos/bin/anaUltraScurve.py", line 759, in <module>
    saveSummary(vSummaryPlots, None, '%s/Summary.png'%filename, trimVcal)
  File "/usr/lib/python2.7/site-packages/gempython/gemplotting/utils/anautilities.py", line 562, in saveSummary
    from mapping.chamberInfo import chamber_vfatPos2PadIdx
  File "/usr/lib64/python2.7/site-packages/ROOT.py", line 318, in _importhook
    return _orig_ihook( name, *args, **kwds )
ImportError: No module named mapping.chamberInfo
```

### Steps to Reproduce (for bugs)
1. ssh to gemuser@gem904qc8daq from lxplus
2. execute "ana_scans.py --scandate=current --ztrim=4 --anaType=scurve  2>&1 | tee -a ana_scurve_log.txt"

## Possible Solution (for bugs)
I have no idea.

## Your Environment
* Version used: Not sure
* Shell used: bash

**Comment by jsturdy** [comment]
Latent broken `import`s from the packaging change
Local fix applied and deployed to the machine for testing
