### ISSUE TITLE
Bug Report: Missing Documentation for anaDACScans.py Crashes Build 

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/gem-plotting-tools#164]
## Brief summary of issue

There seems to be a missing doctree when trying to build `gem-plotting-tools`.

### Types of issue

- [X] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Current Behavior

```bash
% make rpm                                                                                                                
PythonModules=["gempython.gemplotting", "gempython.gemplotting.utils", "gempython.gemplotting.fitting", "gempython.gemplotting.macros", "gempython.gemplotting.mapping" ]
Using BUILD_HOME=/afs/cern.ch/user/d/dorney/scratch0/CMS_GEM/CMS_GEM_DAQ
OS Detected: centos7
BUILD_VERSION 1.0.72.dev
PREREL_VERSION -final.dev72
mkdir -p pkg/gempython/gemplotting
python /usr/bin/sphinx-build -b man -d /afs/cern.ch/user/d/dorney/scratch0/CMS_GEM/CMS_GEM_DAQ/gem-plotting-tools/doc/_build/doctrees   /afs/cern.ch/user/d/dorney/scratch0/CMS_GEM/CMS_GEM_DAQ/gem-plotting-tools/doc /afs/cern.ch/user/d/dorney/scratch0/CMS_GEM/CMS_GEM_DAQ/gem-plotting-tools/doc/_build/man
Running Sphinx v1.1.3
loading pickled environment... done
building [man]: all manpages
updating environment: 0 added, 2 changed, 0 removed
Traceback (most recent call last):ACscan                                                                                                                                                                                                 
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
ImportError: No module named py

/afs/cern.ch/user/d/dorney/scratch0/CMS_GEM/CMS_GEM_DAQ/gem-plotting-tools/doc/man-index.rst:14: WARNING: toctree contains reference to nonexisting document u'man/anaDACScan'
/afs/cern.ch/user/d/dorney/scratch0/CMS_GEM/CMS_GEM_DAQ/gem-plotting-tools/doc/man/anaDACscan.rst:1: WARNING: autodoc can't import/find module 'anaDACScan.py', it reported error: "No module named py", please check your spelling and sys.path
looking for now-outdated files... none found
pickling environment... done
checking consistency... /afs/cern.ch/user/d/dorney/scratch0/CMS_GEM/CMS_GEM_DAQ/gem-plotting-tools/doc/man/anaDACscan.rst:: WARNING: document isn't included in any toctree
done
writing... gemplotting.1 { setup coding virtualenv-p5 scandate-list-formats masking analyzing-scans scurve-plotting-tools man-index man/plot_eff man/gemPlotter man/gemTreeDrawWrapper man/gemSCurveAnaToolkit man/plotSCurveFitResults man/timeHistoryAnalyzer man/clusterAnaScurve man/packageFiles4Docker modules-index modules/fitting/fitScanData modules/mapping/PanChannelMaps modules/mapping/amcInfo modules/mapping/chamberInfo modules/mapping/channelMaps modules/utils/anaInfo modules/utils/anahistory modules/utils/anaoptions modules/utils/anautilities } gemPlotter.py.1 { } gemSCurveAnaToolkit.py.1 { } gemTreeDrawWrapper.py.1 { } packageFiles4Docker.py.1 { } plotSCurveFitResults.py.1 { } plot_eff.py.1 { } anaDACScan.py.1 { 
Exception occurred:
  File "/usr/lib/python2.7/site-packages/sphinx/environment.py", line 1213, in get_doctree
    f = open(doctree_filename, 'rb')
IOError: [Errno 2] No such file or directory: '/afs/cern.ch/user/d/dorney/scratch0/CMS_GEM/CMS_GEM_DAQ/gem-plotting-tools/doc/_build/doctrees/man/anaDACScan.doctree'
The full traceback has been saved in /tmp/dorney/sphinx-err-ucj70E.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
Either send bugs to the mailing list at <http://groups.google.com/group/sphinx-dev/>,
or report them in the tracker at <http://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make: *** [man] Error 1
```

Seems like there is a mixup with the required doc tree:

```
gem-plotting-tools/doc/_build/doctrees/man/anaDACScan.doctree
```

This file does not exist, but...

```bash
% ll _build/doctrees/man | grep "DAC" --color
-rw-r--r--. 1 dorney zh 2.7K Nov  8 11:11 anaDACscan.doctree
```

This file *does* exist.  So in the build it's looking for `anaDACScan.doctree` with capital `S` while the file that exists is `anaDACscan.doctree` with lower case `s`.  Not sure what is creating this file so I am unable to fix it.

Additionally there is another error above that I'm unsure about:

```
Traceback (most recent call last):ACscan                                                                                                                                                                                                 
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
ImportError: No module named py
```

### Steps to Reproduce (for bugs)

1. `git fetch -p`
2. Update to `HEAD` of `develop`
3. execute `make clean && make rpm`

## Possible Solution (for bugs)

Fix some typos somewhere...unsure where.

## Context (for feature requests)

Unable to build the package out of the box.

## Your Environment

* Version used: 44030d02e019c065e0e9cec140f77740b65c9692
* Shell used: `/bin/zsh`

**Comment by bdorney** [comment]
@AndrewLevin seems like when you where making:

https://github.com/cms-gem-daq-project/gem-plotting-tools/pull/158

You did not try to rebuild the package after making the following commit:

https://github.com/cms-gem-daq-project/gem-plotting-tools/pull/158/commits/d6123643ca71ebfe099c3922f5822f6bc5a40111

I am not sure if this is the exact one since many of the commits you made have non-descriptive commit messages.

**Comment by AndrewLevin** [comment]
Sorry about this. Here is the bugfix: https://github.com/cms-gem-daq-project/gem-plotting-tools/pull/165
